#!/usr/bin/env bash
# Installing nginx

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo echo "Holberton School for the win!" | sudo tee /var/www/html/index.nginx-debian.html

searchString="^\tlocation / {"
replaceString="\tlocation /redirect_me {\n\t\treturn 301 \$scheme://https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n\n\tlocation / {"

sed -i "s@${searchString}@${repalceString}@" /etc/ngix/sites-available/default

sudo service nginx restart