#!/usr/bin/env bash
#Write a Bash script that displays Holberton School 10 times, and on the
#9th itteration it displays Hi.
i=0
while [ $i -lt 10 ]
do
    if [[ "$i" == "9" ]];
    then
        echo Hi
    fi
    echo Holberton School
    ((i++))
done
