#!/usr/bin/env bash
#Write a Bash script thatWrite a Bash script that loops from 1 to 10 and:
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Holberton School for the other iterations
i=1
while [ $i -le 20 ]
do
    if [[ "$i" == "4" ]];
    then
        echo $i
        echo bad luck from China
    elif [[ "$i" == "9" ]];
    then
        echo $i
        echo bad luck from Japan
    elif [[ "$i" == "17" ]];
    then
        echo $i
        echo bad luck from Italy
    else
        echo $i
    fi
    ((i++))
done
