#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:

#display hours from 0 to 12
#display minutes from 1 to 59
#Requirements:

#You must use the while loop (for and until are forbidden)
x=1
y=0
while [ $y -le 12 ]; do
    echo Hour: $y
    while [ $x -lt 60 ]; do
        echo $x
        ((x++))
    done
    x=1
    ((y++))
done
